#!/usr/bin/env python3
"""SessionStart hook (matcher: compact|resume): give a compacted or resumed
PROJECT MANAGER its bearings back, and say nothing to anybody else.

A manager that has lost its context mid-loop is the dangerous case: it does
not know which claims it made, so it can claim a second supervisor onto a task
that already has one -- the single failure the board's lock exists to prevent.
It cannot know that from a summary, because a summary of a loop reads like a
description of a loop.

Keyed on the marker the `run` skill writes at startup:
`<project>/devteam/.run/session/manager` holds the session id. This prints
only when that id equals the session being restored. Every other session, in
every other directory, gets nothing -- a hook that talks to sessions it was
not meant for is a hook that gets removed.

**That keying already does most of the rotation's work.** After a rotation the
marker holds the SUCCESSOR's id, so a compacted PREDECESSOR matches nothing
and is told nothing -- correct, because it has been replaced and has no
business acting. And an outgoing manager that compacts after writing
`handoff-ready` but before anyone arrives still matches, is still told to
continue its loop, and is told nothing extra -- also correct, because that
file names itself and `run` §7b step 4 says keep working.

**The one case left is the SUCCESSOR mid-handoff**, and it is why the rotation
line is conditional rather than printed always. A successor that has taken the
lock but not yet finished -- told its predecessor, removed the file -- and
then compacts, would otherwise read a perfectly ordinary bearings block and
carry on as though it had always been the manager, leaving a predecessor that
was never told to stop and an untracked file nobody accounts for. So the line
prints exactly when `handoff-ready` names somebody who is not the reader.

The block is a POINTER AND A PROCEDURE, never the rules themselves (P-34).
The rules have one home: skills/run/SKILL.md.
"""
import json
import os
import sys

BLOCK = """PROJECT MANAGER — context restored after compaction or resume.

You are the project manager for the devteam project at {project}.
Procedure: skills/run/SKILL.md — the loop is §4, reports are §6, escalation
classes are §8. Live state: devteam/BOARD.md. Past: devteam/RECORD.md.

Before any further action:
  1. re-read devteam/BOARD.md — it, not your memory, is the state;
  2. run ListAgents and reconcile the in-flight table. A row with no live
     agent is STALE: §3 Recovery. After a resume, EVERY row is stale;
  3. do not redo what the board shows done — the environment pin, the
     claims already made, the questions already on the table;
  4. width, the model band and the escalation window come from the board
     header and the charter, never from what you remember deciding.

Then continue the loop. If you cannot tell whether a task is claimed, read
the board's git history — a claim is a commit."""

ROTATION = """
A ROTATION IS IN PROGRESS. devteam/.run/session/handoff-ready names session
{other}, which is not you. Read skills/resume/SKILL.md §0 before you touch the
board — you may be the manager that was replaced, and you must not re-take a
lock you have already lost."""

ROTATION_MALFORMED = """
devteam/.run/session/handoff-ready EXISTS BUT IS MALFORMED: {why}. That file
is only ever written by a rotation (run §7b), so treat a rotation as in
progress and read skills/resume/SKILL.md §0 before you touch the board. Do not
assume it means nothing because it does not parse."""


def find_project(start):
    cur = os.path.realpath(start)
    while True:
        if os.path.isdir(os.path.join(cur, "devteam")):
            return cur
        parent = os.path.dirname(cur)
        if parent == cur:
            return None
        cur = parent


def handoff_state(project):
    """(state, detail) for `devteam/.run/session/handoff-ready`.

    States are `absent`, `malformed` with the reason, `named` with the session
    id while a rotation is in progress, and `completed` with it once the
    successor has finished. The file is a POINTER written by `run` §7b --
    `session <id>` then `checkpoint C-n` -- because everything volatile is
    generated by the reader instead of recorded by the writer. The successor
    appends `completed <iso> by <id>` rather than deleting the file (`resume`
    §0 step 6): the guard needs it afterwards to tell a REPLACED manager from
    a stranger, and those two get opposite advice.

    **Both lines are required and the id must be non-empty.** A file naming a
    session but no checkpoint is a half-written handoff, and a `session ` with
    nothing after it is the blank-id failure that inverted the guard's writer
    check: an id that expands to nothing does not read as absent, it reads as
    somebody else. Malformed is reported rather than swallowed, because this
    file is only ever written by a rotation -- so an unparseable one still
    means a rotation is happening, and silence would tell a replaced manager
    to carry on.
    """
    path = os.path.join(project, "devteam", ".run", "session", "handoff-ready")
    try:
        with open(path, encoding="utf-8") as fh:
            lines = [ln.strip() for ln in fh.read().split("\n") if ln.strip()]
    except OSError:
        return "absent", ""
    session = checkpoint = ""
    done = False
    for ln in lines:
        key, _, rest = ln.partition(" ")
        if key == "session" and not session:
            session = rest.strip()
        elif key == "checkpoint" and not checkpoint:
            checkpoint = rest.strip()
        elif key == "completed":
            done = True
    if not session:
        return "malformed", "no `session <id>` line, or the id is empty"
    if not checkpoint:
        return "malformed", "no `checkpoint C-n` line"
    return ("completed" if done else "named"), session


def main():
    try:
        data = json.load(sys.stdin)
    except Exception:
        return 0
    sid = str(data.get("session_id") or "")
    if not sid:
        return 0
    start = os.environ.get("CLAUDE_PROJECT_DIR") or data.get("cwd") or os.getcwd()
    project = find_project(start)
    if project is None:
        return 0
    marker = os.path.join(project, "devteam", ".run", "session", "manager")
    try:
        with open(marker, encoding="utf-8") as fh:
            marked = fh.read().strip()
    except OSError:
        return 0
    if marked != sid:
        return 0
    out = BLOCK.format(project=project)
    state, detail = handoff_state(project)
    if state == "malformed":
        out += ROTATION_MALFORMED.format(why=detail)
    elif state == "named" and detail != sid:
        out += ROTATION.format(other=detail)
    print(out)
    return 0


if __name__ == "__main__":
    sys.exit(main())
